version: '3'

services:
  app:
    build: .
    entrypoint: ["npm", "run", "docker:app"]
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  api:
    build: .
    entrypoint: ["npm", "run", "docker:api"]
    ports:
      - 8000:8000
    volumes:
      - .:/home/node/app
